### ISSUE TITLE
how to solve the error 'ValueError: too many values to unpack (expected 2)'

### ISSUE THREAD

**Issue by Truant-jason** [yaoppeng/U-Net_v2#9]
Traceback (most recent call last):
  File "D:\Unet V2\PolypSeg\Train.py", line 341, in <module>
    train(train_loader, model, optimizer, epoch, opt.test_path)
  File "D:\Unet V2\PolypSeg\Train.py", line 145, in train
    P1, P2= model(images)
ValueError: too many values to unpack (expected 2)

**Comment by yaoppeng** [comment]
Sorry about the mistake. I forget about uncomment the code, in lib/pvt3.py:

```
if self.deep_supervision:
    return F.interpolate(out1, scale_factor=8, mode='bilinear'), \
                F.interpolate(out2, scale_factor=4, mode='bilinear')
else:
    return F.interpolate(out2, scale_factor=4, mode='bilinear')
```

**Comment by Wxy19992** [comment]
> 很抱歉这个错误。我忘了取消注释 lib/pvt_3.py 中的代码。修复了它。
> 
> ```
> if self.deep_supervision:
>     return F.interpolate(out1, scale_factor=8, mode='bilinear'), \
>                 F.interpolate(out2, scale_factor=4, mode='bilinear')
> else:
>     return F.interpolate(out2, scale_factor=4, mode='bilinear')
> ```
Hello, I have modified according to your instructions, but it still doesn't work. What is the reason?

**Comment by yaoppeng** [comment]
This is related to the self supervision switch. In the training stage, `deep_supervision` should be True. While in the test stage, `deep_supervision` should be False.

**Comment by yaoppeng** [comment]
fixed.
